create table if not exists public.hog_stages (
  stage_id bigint generated by default as identity primary key,
  stage_name text not null,
  feed_type text,
  stage_order integer not null,
  is_final boolean not null default false,
  hog_type_id bigint not null references public.hog_types(hog_type_id) on delete restrict,
  unique(hog_type_id, stage_order),
  unique(hog_type_id, stage_name)
);
