create table if not exists public.hogs (
  hog_id bigint generated by default as identity primary key,
  status text not null default 'active',
  health_status text,
  last_updated timestamptz not null default now(),
  assignment_id bigint not null references public.assignments(assignment_id) on delete restrict,
  stage_id bigint references public.hog_stages(stage_id) on delete set null
);

create index if not exists idx_hogs_assignment on public.hogs(assignment_id);
create index if not exists idx_hogs_stage on public.hogs(stage_id);
