create table if not exists public.hog_stage_logs (
  stage_log_id bigint generated by default as identity primary key,
  date_started date not null,
  date_ended date,
  hog_id bigint not null references public.hogs(hog_id) on delete cascade,
  stage_id bigint not null references public.hog_stages(stage_id) on delete restrict,
  check (date_ended is null or date_ended >= date_started)
);

create index if not exists idx_hog_stage_logs_hog on public.hog_stage_logs(hog_id);
