create table if not exists public.capital_infusions (
  capital_id bigint generated by default as identity primary key,
  amount numeric(14,2) not null check (amount >= 0),
  date_processed date not null default current_date,
  request_id bigint not null references public.stock_requests(request_id) on delete cascade
);

create index if not exists idx_capital_infusions_request on public.capital_infusions(request_id);
