create table if not exists public.supply (
  supply_id bigint generated by default as identity primary key,
  quantity_added integer not null check (quantity_added > 0),
  date_added date not null default current_date,
  product_id bigint not null references public.products(product_id) on delete restrict
);

create index if not exists idx_supply_product on public.supply(product_id);
