create table if not exists public.investments (
  investment_id bigint generated by default as identity primary key,
  amount numeric(14,2) not null check (amount >= 0),
  date_invested date not null default current_date,
  status text not null default 'active',
  batch_id bigint not null references public.batches(batch_id) on delete restrict,
  partner_investor_id bigint not null references public.partner_investors(partner_investor_id) on delete restrict
);

create index if not exists idx_investments_batch on public.investments(batch_id);
create index if not exists idx_investments_partner on public.investments(partner_investor_id);
