-- 1. Create admin_notifications table
create table if not exists public.admin_notifications (
  notification_id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  type text not null, -- 'stock_request', 'new_raiser'
  is_read boolean not null default false,
  metadata jsonb, -- e.g. { "request_id": 12, "hog_raiser_id": 3, "raiser_name": "Juan" }
  created_at timestamptz not null default now()
);

-- Index for unread notifications
create index if not exists idx_admin_notifications_unread 
  on public.admin_notifications(is_read) 
  where is_read = false;

-- 2. Trigger on stock_requests insert
create or replace function public.notify_admin_on_stock_request()
returns trigger as $$
declare
  raiser_name text;
begin
  select name into raiser_name 
  from public.hog_raisers 
  where hog_raiser_id = new.hog_raiser_id;

  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Stock Request',
    coalesce(raiser_name, 'A hog raiser') || ' has requested new stocks.',
    'stock_request',
    jsonb_build_object(
      'request_id', new.request_id,
      'hog_raiser_id', new.hog_raiser_id,
      'raiser_name', raiser_name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_stock_request_insert
after insert on public.stock_requests
for each row execute function public.notify_admin_on_stock_request();

-- 3. Trigger on hog_raisers insert
create or replace function public.notify_admin_on_new_raiser()
returns trigger as $$
begin
  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Hog Raiser Registered',
    coalesce(new.name, 'A new raiser') || ' registered and is pending approval.',
    'new_raiser',
    jsonb_build_object(
      'hog_raiser_id', new.hog_raiser_id,
      'raiser_name', new.name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_hog_raiser_insert
after insert on public.hog_raisers
for each row execute function public.notify_admin_on_new_raiser();

-- 4. Trigger on hog_raisers update (lifecycle_stage progress change)
create or replace function public.notify_admin_on_raiser_stage_update()
returns trigger as $$
begin
  if old.lifecycle_stage is distinct from new.lifecycle_stage and new.lifecycle_stage is not null then
    insert into public.admin_notifications (title, message, type, metadata)
    values (
      'Raiser Progress Updated',
      coalesce(new.name, 'A hog raiser') || ' has updated their progress stage to ' || new.lifecycle_stage || '.',
      'progress_update',
      jsonb_build_object(
        'hog_raiser_id', new.hog_raiser_id,
        'raiser_name', new.name,
        'old_stage', old.lifecycle_stage,
        'new_stage', new.lifecycle_stage
      )
    );
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_raiser_stage_update
after update of lifecycle_stage on public.hog_raisers
for each row execute function public.notify_admin_on_raiser_stage_update();

-- 5. Trigger on partner_investors insert
create or replace function public.notify_admin_on_new_partner()
returns trigger as $$
declare
  partner_name text;
begin
  select name into partner_name 
  from public.app_users 
  where user_id = new.user_id;

  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Partner Investor Registered',
    coalesce(partner_name, 'A new partner') || ' registered and is pending approval.',
    'new_partner',
    jsonb_build_object(
      'partner_investor_id', new.partner_investor_id,
      'partner_name', partner_name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_partner_investor_insert
after insert on public.partner_investors
for each row execute function public.notify_admin_on_new_partner();

-- 6. Trigger on cashiers insert
create or replace function public.notify_admin_on_new_cashier()
returns trigger as $$
declare
  cashier_name text;
begin
  select name into cashier_name 
  from public.app_users 
  where user_id = new.user_id;

  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Cashier Registered',
    coalesce(cashier_name, 'A new cashier') || ' registered and is pending approval.',
    'new_cashier',
    jsonb_build_object(
      'cashier_id', new.cashier_id,
      'cashier_name', cashier_name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_cashier_insert
after insert on public.cashiers
for each row execute function public.notify_admin_on_new_cashier();
