-- 40_partner_notifications.sql
-- Create partner_notifications table and setup auto-notification triggers for Partner Investors.

begin;

-- 1. Create partner_notifications table
create table if not exists public.partner_notifications (
  notification_id bigint generated by default as identity primary key,
  partner_investor_id bigint not null references public.partner_investors(partner_investor_id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'general', -- 'hog_report', 'stage_update', 'investment_confirmed', 'batch_update'
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- Index for unread notifications per partner
create index if not exists idx_partner_notifications_unread 
  on public.partner_notifications(partner_investor_id, is_read) 
  where is_read = false;

create index if not exists idx_partner_notifications_created 
  on public.partner_notifications(created_at desc);

-- Enable RLS
alter table public.partner_notifications enable row level security;

-- Policy for partner investors to read and update notifications
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'partner_notifications'
      and policyname = 'partner_notifications_auth_all'
  ) then
    create policy partner_notifications_auth_all on public.partner_notifications
      for all to authenticated
      using (true)
      with check (true);
  end if;
end $$;

-- 2. Trigger on hog_reports insert: Notify Partner Investors of Raiser Activities
create or replace function public.notify_partners_on_hog_report()
returns trigger as $$
declare
  r_name text;
  b_id bigint;
  b_name text;
  partner_rec record;
  partner_count int := 0;
begin
  -- Fetch the raiser's name
  select name into r_name 
  from public.hog_raisers 
  where hog_raiser_id = new.hog_raiser_id;

  -- Find the batch associated with this hog/raiser
  select a.batch_id, b.batch_name into b_id, b_name
  from public.assignments a
  left join public.batches b on b.batch_id = a.batch_id
  where a.hog_raiser_id = new.hog_raiser_id
  order by a.assigned_date desc
  limit 1;

  -- Notify all partners who invested in this batch
  if b_id is not null then
    for partner_rec in (
      select distinct partner_investor_id 
      from public.investments 
      where batch_id = b_id
    ) loop
      partner_count := partner_count + 1;
      insert into public.partner_notifications (partner_investor_id, title, message, type, metadata)
      values (
        partner_rec.partner_investor_id,
        'Hog Raiser Update: ' || coalesce(new.report_type, 'Activity'),
        coalesce(r_name, 'Your hog raiser') || ' logged an update for ' || coalesce(b_name, 'Batch #' || b_id) || ': ' || coalesce(new.description, new.report_type) || '.',
        'hog_report',
        jsonb_build_object(
          'report_id', new.report_id,
          'hog_id', new.hog_id,
          'hog_raiser_id', new.hog_raiser_id,
          'raiser_name', r_name,
          'batch_id', b_id,
          'batch_name', b_name,
          'report_type', new.report_type,
          'description', new.description
        )
      );
    end loop;
  end if;

  -- If no partners invested specifically in this batch yet, notify all active partners as a general farm activity
  if partner_count = 0 then
    for partner_rec in (
      select partner_investor_id 
      from public.partner_investors
    ) loop
      insert into public.partner_notifications (partner_investor_id, title, message, type, metadata)
      values (
        partner_rec.partner_investor_id,
        'Farm Update: ' || coalesce(new.report_type, 'Activity'),
        coalesce(r_name, 'Hog raiser') || ' posted a new log: ' || coalesce(new.description, new.report_type) || '.',
        'hog_report',
        jsonb_build_object(
          'report_id', new.report_id,
          'hog_id', new.hog_id,
          'hog_raiser_id', new.hog_raiser_id,
          'raiser_name', r_name,
          'report_type', new.report_type,
          'description', new.description
        )
      );
    end loop;
  end if;

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_notify_partners_on_hog_report on public.hog_reports;
create trigger trigger_notify_partners_on_hog_report
after insert on public.hog_reports
for each row execute function public.notify_partners_on_hog_report();


-- 3. Trigger on investments insert: Notify Partner Investor of confirmed investment
create or replace function public.notify_partner_on_investment_confirmed()
returns trigger as $$
declare
  b_name text;
begin
  select batch_name into b_name 
  from public.batches 
  where batch_id = new.batch_id;

  insert into public.partner_notifications (partner_investor_id, title, message, type, metadata)
  values (
    new.partner_investor_id,
    'Investment Confirmed',
    'Your investment of ₱' || to_char(new.amount, 'FM999,999,990.00') || ' in ' || coalesce(b_name, 'Batch #' || new.batch_id) || ' has been successfully confirmed.',
    'investment_confirmed',
    jsonb_build_object(
      'investment_id', new.investment_id,
      'batch_id', new.batch_id,
      'batch_name', b_name,
      'amount', new.amount
    )
  );

  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trigger_notify_partner_on_investment on public.investments;
create trigger trigger_notify_partner_on_investment
after insert on public.investments
for each row execute function public.notify_partner_on_investment_confirmed();

commit;

notify pgrst, 'reload schema';
