create table if not exists public.cashiers (
  cashier_id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  date_hired date not null default current_date,
  status text not null default 'active',
  avatar_url text
);

create index if not exists idx_cashiers_user_id on public.cashiers(user_id);
