create table if not exists public.logs (
  logs_id bigint generated by default as identity primary key,
  status text,
  login_attempts integer not null default 0,
  user_id bigint not null references public.app_users(user_id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_logs_user_id on public.logs(user_id);
