create table if not exists public.batches (
  batch_id bigint generated by default as identity primary key,
  batch_name text not null unique,
  date_created date not null default current_date,
  status text not null default 'Active'
);

create index if not exists idx_batches_status on public.batches(status);
