create table if not exists public.partner_investors (
  partner_investor_id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  address text,
  contact_number text,
  registration_date date not null default current_date
);
