create table if not exists public.hog_raisers (
  hog_raiser_id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  address text,
  phone text,
  email text,
  account_status text not null default 'active',
  name text,
  pig_type text not null default 'Fattening',
  status text not null default 'Active',
  lifecycle_stage text not null default 'Booster',
  avatar_url text
);

create index if not exists idx_hog_raisers_user_id on public.hog_raisers(user_id);
create index if not exists idx_hog_raisers_status on public.hog_raisers(account_status);
