create table if not exists public.hog_raisers (
  hog_raiser_id bigint generated by default as identity primary key,
  address text,
  contact_number text,
  account_status text not null default 'active',
  user_id bigint not null unique references public.app_users(user_id) on delete cascade
);

create index if not exists idx_hog_raisers_status on public.hog_raisers(account_status);
