create table if not exists public.hog_raisers (
  hog_raiser_id bigint generated by default as identity primary key,
  address text,
  phone text,                  -- Changed from contact_number to match active code
  email text,                  -- Required by auth signup trigger
  account_status text not null default 'active',
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  
  -- Performance Denormalization Columns (added for optimized dashboard reads)
  name text,
  pig_type text not null default 'Fattening',
  status text not null default 'Active',
  lifecycle_stage text not null default 'Booster'
);

create index if not exists idx_hog_raisers_status on public.hog_raisers(account_status);
