create table if not exists public.hogs (
  hog_id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(assignment_id) on delete cascade,
  status text not null default 'active',
  health_status text not null default 'healthy',
  weight numeric(6,2) default 15.0,
  last_updated timestamptz not null default now()
);

create index if not exists idx_hogs_assignment on public.hogs(assignment_id);
create index if not exists idx_hogs_status on public.hogs(status);
