create table if not exists public.assignments (
  assignment_id bigint generated by default as identity primary key,
  assigned_date date not null default current_date,
  status text not null default 'active',
  hog_type_id bigint not null references public.hog_types(hog_type_id) on delete restrict,
  batch_id bigint not null references public.batches(batch_id) on delete restrict,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete restrict
);

create index if not exists idx_assignments_raiser on public.assignments(hog_raiser_id);
create index if not exists idx_assignments_batch on public.assignments(batch_id);
