create table if not exists public.stock_requests (
  request_id bigint generated by default as identity primary key,
  request_date date not null default current_date,
  status text not null default 'pending',
  decision_date date,
  assignment_id bigint references public.assignments(assignment_id) on delete set null,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  category text not null default 'Feeds',
  quantity integer not null default 1,
  feed_type text,
  notes text
);

create index if not exists idx_stock_requests_assignment on public.stock_requests(assignment_id);
create index if not exists idx_stock_requests_raiser on public.stock_requests(hog_raiser_id);
create index if not exists idx_stock_requests_status on public.stock_requests(status);
