create table if not exists public.stock_requests (
  request_id bigint generated by default as identity primary key,
  request_date date not null default current_date,
  status text not null default 'pending',
  decision_date date,
  assignment_id bigint not null references public.assignments(assignment_id) on delete restrict,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete restrict
);

create index if not exists idx_stock_requests_assignment on public.stock_requests(assignment_id);
