create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  current_stock integer not null default 0 check (current_stock >= 0),
  category text
);

create index if not exists idx_products_category on public.products(category);
