  create table if not exists public.sales (
    sale_id bigint generated by default as identity primary key,
    quantity integer not null check (quantity > 0),
    total_amount numeric(14,2) not null check (total_amount >= 0),
    sale_date timestamptz not null default now(),
    type text,
    product_id bigint not null references public.products(product_id) on delete restrict,
    hog_raiser_id bigint references public.hog_raisers(hog_raiser_id) on delete set null,
    performed_by bigint not null references public.app_users(user_id) on delete restrict
  );

  create index if not exists idx_sales_product on public.sales(product_id);
  create index if not exists idx_sales_hog_raiser on public.sales(hog_raiser_id);
