create table if not exists public.hog_reports (
  report_id bigint generated by default as identity primary key,
  hog_id bigint not null references public.hogs(hog_id) on delete cascade,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  report_type text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_hog_reports_hog on public.hog_reports(hog_id);
create index if not exists idx_hog_reports_raiser on public.hog_reports(hog_raiser_id);
create index if not exists idx_hog_reports_created on public.hog_reports(created_at desc);
