create table if not exists public.admin_notifications (
  notification_id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  type text not null,
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_admin_notifications_unread 
  on public.admin_notifications(is_read) 
  where is_read = false;

create index if not exists idx_admin_notifications_created 
  on public.admin_notifications(created_at desc);
