create table if not exists public.raiser_notifications (
  notification_id bigint generated by default as identity primary key,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  title text not null,
  message text not null,
  type text not null,
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_raiser_notifications_unread 
  on public.raiser_notifications(hog_raiser_id, is_read) 
  where is_read = false;

create index if not exists idx_raiser_notifications_created 
  on public.raiser_notifications(created_at desc);
