create table if not exists public.partner_notifications (
  notification_id bigint generated by default as identity primary key,
  partner_investor_id bigint not null references public.partner_investors(partner_investor_id) on delete cascade,
  title text not null,
  message text not null,
  type text not null default 'general',
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_partner_notifications_unread 
  on public.partner_notifications(partner_investor_id, is_read) 
  where is_read = false;

create index if not exists idx_partner_notifications_created 
  on public.partner_notifications(created_at desc);
