create table if not exists public.hog_reports (
  report_id bigint generated by default as identity primary key,
  hog_id bigint not null references public.hogs(hog_id) on delete cascade,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  report_type text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_hog_reports_hog on public.hog_reports(hog_id);
create index if not exists idx_hog_reports_raiser on public.hog_reports(hog_raiser_id);

-- Enable RLS and allow all actions for simplicity during development
alter table public.hog_reports enable row level security;

create policy "Allow all on hog_reports"
on public.hog_reports
for all
using (true)
with check (true);
