-- ==============================================================================
-- 29_admin_password_resets.sql
-- Table: public.admin_password_resets
-- Purpose: Temporary storage and auditing of 6-digit OTP codes for password recovery.
-- Normal Form: 3NF (Atomic fields, single-column PK, no partial or transitive dependencies)
-- ==============================================================================

begin;

-- Ensure pgcrypto extension is active for security hashing
create extension if not exists pgcrypto with schema extensions;

-- 1. Table to hold reset OTPs
create table if not exists public.admin_password_resets (
  id bigint generated by default as identity primary key,
  email text not null,
  otp_code text not null,
  expires_at timestamptz not null,
  used boolean default false,
  created_at timestamptz default now()
);

-- Fast lookup index for active, unexpired OTP verification
create index if not exists idx_admin_password_resets_lookup 
on public.admin_password_resets (lower(email), otp_code, used);

-- Enable RLS and grant access
alter table public.admin_password_resets enable row level security;

drop policy if exists admin_resets_full_access on public.admin_password_resets;
create policy admin_resets_full_access on public.admin_password_resets
  for all to public
  using (true)
  with check (true);

commit;
