-- 29_raiser_notifications.sql
-- Create raiser_notifications table and setup auto-notification triggers for mobile users.

begin;

-- 1. Create table
create table if not exists public.raiser_notifications (
  notification_id bigint generated by default as identity primary key,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  title text not null,
  message text not null,
  type text not null, -- 'request_status', 'batch_assigned', etc.
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

-- Index for unread notifications
create index if not exists idx_raiser_notifications_unread 
  on public.raiser_notifications(hog_raiser_id, is_read) 
  where is_read = false;

-- Enable RLS
alter table public.raiser_notifications enable row level security;

-- Policy for raisers to read and update their own notifications
create policy raiser_notifications_auth_all on public.raiser_notifications
  for all to authenticated
  using (true)
  with check (true);

-- 2. Trigger on stock_requests update (notify raiser when status changes)
create or replace function public.notify_raiser_on_request_update()
returns trigger as $$
begin
  if (old.status is distinct from new.status) then
    insert into public.raiser_notifications (hog_raiser_id, title, message, type, metadata)
    values (
      new.hog_raiser_id,
      'Stock Request Update',
      'Your request for ' || new.quantity || ' ' || coalesce(new.category, 'supplies') || ' has been ' || lower(new.status) || '.',
      'request_status',
      jsonb_build_object(
        'request_id', new.request_id,
        'status', new.status,
        'category', new.category,
        'quantity', new.quantity
      )
    );
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_stock_request_update
after update of status on public.stock_requests
for each row execute function public.notify_raiser_on_request_update();

-- 3. Trigger on investment_records insert (notify raiser when a batch is assigned)
create or replace function public.notify_raiser_on_investment()
returns trigger as $$
begin
  insert into public.raiser_notifications (hog_raiser_id, title, message, type, metadata)
  values (
    (new.hog_raiser_id)::bigint,
    'New Batch Assigned',
    'A new active batch of ' || new.total_hog || ' ' || new.hog_type || ' has been assigned to you.',
    'batch_assigned',
    jsonb_build_object(
      'investment_id', new.id,
      'hog_type', new.hog_type,
      'total_hog', new.total_hog
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_investment_insert
after insert on public.investment_records
for each row execute function public.notify_raiser_on_investment();

commit;
