-- PiggyTrunk full database setup for Supabase.
-- Run this whole script once in Supabase SQL Editor.

begin;

-- =========================
-- TABLES
-- =========================

create table if not exists public.hog_raisers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  address text not null,
  pig_type text not null,
  status text not null default 'Active',
  lifecycle_stage text,
  created_at timestamptz not null default now()
);

-- Keep this idempotent even if table existed with partial columns.
alter table public.hog_raisers
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists address text,
  add column if not exists pig_type text,
  add column if not exists status text,
  add column if not exists lifecycle_stage text,
  add column if not exists created_at timestamptz not null default now();

update public.hog_raisers
set
  name = coalesce(nullif(trim(name), ''), 'Unknown Raiser'),
  phone = coalesce(nullif(trim(phone), ''), '00000000000'),
  email = coalesce(nullif(trim(email), ''), 'unknown@example.com'),
  address = coalesce(nullif(trim(address), ''), 'Unknown Address'),
  pig_type = coalesce(nullif(trim(pig_type), ''), 'Fattening'),
  status = coalesce(nullif(trim(status), ''), 'Active'),
  lifecycle_stage = coalesce(nullif(trim(lifecycle_stage), ''), 'Pre-Starter');

alter table public.hog_raisers
  alter column name set not null,
  alter column phone set not null,
  alter column email set not null,
  alter column address set not null,
  alter column pig_type set not null,
  alter column status set not null;

create table if not exists public.inventory_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category_id text not null,
  category text not null,
  image text,
  description text not null default '',
  price numeric(12,2) not null check (price >= 0),
  units integer not null default 0 check (units >= 0),
  sold integer not null default 0 check (sold >= 0),
  is_archived boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.inventory_products
  add column if not exists name text,
  add column if not exists category_id text,
  add column if not exists category text,
  add column if not exists image text,
  add column if not exists description text,
  add column if not exists price numeric(12,2),
  add column if not exists units integer,
  add column if not exists sold integer,
  add column if not exists is_archived boolean,
  add column if not exists created_at timestamptz not null default now();

update public.inventory_products
set
  name = coalesce(nullif(trim(name), ''), 'Untitled Product'),
  category_id = coalesce(nullif(trim(category_id), ''), 'others'),
  category = coalesce(nullif(trim(category), ''), 'Others'),
  description = coalesce(description, ''),
  price = coalesce(price, 0),
  units = coalesce(units, 0),
  sold = coalesce(sold, 0),
  is_archived = coalesce(is_archived, false);

alter table public.inventory_products
  alter column name set not null,
  alter column category_id set not null,
  alter column category set not null,
  alter column description set not null,
  alter column price set not null,
  alter column units set not null,
  alter column sold set not null,
  alter column is_archived set not null;

create table if not exists public.investments (
  id bigint generated by default as identity primary key,
  hog_raiser_id bigint not null references public.hog_raisers(id) on delete restrict,
  raiser_name text not null,
  initial_capital numeric(14,2) not null check (initial_capital >= 0),
  hog_type text not null,
  total_hog integer not null check (total_hog > 0),
  investment_date timestamptz not null,
  stage text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.investments
  add column if not exists hog_raiser_id bigint,
  add column if not exists raiser_name text,
  add column if not exists initial_capital numeric(14,2),
  add column if not exists hog_type text,
  add column if not exists total_hog integer,
  add column if not exists investment_date timestamptz,
  add column if not exists stage text,
  add column if not exists created_at timestamptz not null default now();

update public.investments
set
  raiser_name = coalesce(nullif(trim(raiser_name), ''), 'Unknown Raiser'),
  initial_capital = coalesce(initial_capital, 0),
  hog_type = coalesce(nullif(trim(hog_type), ''), 'Fattening'),
  total_hog = greatest(coalesce(total_hog, 1), 1),
  investment_date = coalesce(investment_date, now()),
  stage = coalesce(nullif(trim(stage), ''), 'pending');

alter table public.investments
  alter column hog_raiser_id set not null,
  alter column raiser_name set not null,
  alter column initial_capital set not null,
  alter column hog_type set not null,
  alter column total_hog set not null,
  alter column investment_date set not null,
  alter column stage set not null;

-- =========================
-- CONSTRAINTS AND INDEXES
-- =========================

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'hog_raisers_pig_type_check'
  ) then
    alter table public.hog_raisers
      add constraint hog_raisers_pig_type_check
      check (pig_type in ('Fattening', 'Sow'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'hog_raisers_status_check'
  ) then
    alter table public.hog_raisers
      add constraint hog_raisers_status_check
      check (status in ('Active', 'Inactive'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'hog_raisers_lifecycle_stage_check'
  ) then
    alter table public.hog_raisers
      add constraint hog_raisers_lifecycle_stage_check
      check (
        lifecycle_stage is null
        or lifecycle_stage in ('Booster', 'Pre-Starter', 'Starter', 'Grower', 'Finisher', 'Selling')
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'investments_stage_check'
  ) then
    alter table public.investments
      add constraint investments_stage_check
      check (lower(stage) in ('pending', 'active', 'completed'));
  end if;
end
$$;

create unique index if not exists hog_raisers_email_unique_idx
  on public.hog_raisers (lower(email));

create index if not exists idx_hog_raisers_status
  on public.hog_raisers (status);

create index if not exists idx_inventory_products_archived_created
  on public.inventory_products (is_archived, created_at desc);

create index if not exists idx_investments_raiser_date
  on public.investments (hog_raiser_id, investment_date desc);

-- =========================
-- STORAGE BUCKETS
-- =========================

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('profile_pictures', 'profile_pictures', true)
on conflict (id) do nothing;

-- =========================
-- RLS + POLICIES
-- =========================

alter table public.hog_raisers enable row level security;
alter table public.inventory_products enable row level security;
alter table public.investments enable row level security;

-- hog_raisers policies
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'hog_raisers' and policyname = 'hog_raisers_select_authenticated'
  ) then
    create policy hog_raisers_select_authenticated on public.hog_raisers for select to authenticated using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'hog_raisers' and policyname = 'hog_raisers_insert_authenticated'
  ) then
    create policy hog_raisers_insert_authenticated on public.hog_raisers for insert to authenticated with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'hog_raisers' and policyname = 'hog_raisers_update_authenticated'
  ) then
    create policy hog_raisers_update_authenticated on public.hog_raisers for update to authenticated using (true) with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'hog_raisers' and policyname = 'hog_raisers_delete_authenticated'
  ) then
    create policy hog_raisers_delete_authenticated on public.hog_raisers for delete to authenticated using (true);
  end if;
end
$$;

-- inventory_products policies
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'inventory_products' and policyname = 'inventory_products_select_authenticated'
  ) then
    create policy inventory_products_select_authenticated on public.inventory_products for select to authenticated using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'inventory_products' and policyname = 'inventory_products_insert_authenticated'
  ) then
    create policy inventory_products_insert_authenticated on public.inventory_products for insert to authenticated with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'inventory_products' and policyname = 'inventory_products_update_authenticated'
  ) then
    create policy inventory_products_update_authenticated on public.inventory_products for update to authenticated using (true) with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'inventory_products' and policyname = 'inventory_products_delete_authenticated'
  ) then
    create policy inventory_products_delete_authenticated on public.inventory_products for delete to authenticated using (true);
  end if;
end
$$;

-- investments policies
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'investments' and policyname = 'investments_select_authenticated'
  ) then
    create policy investments_select_authenticated on public.investments for select to authenticated using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'investments' and policyname = 'investments_insert_authenticated'
  ) then
    create policy investments_insert_authenticated on public.investments for insert to authenticated with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'investments' and policyname = 'investments_update_authenticated'
  ) then
    create policy investments_update_authenticated on public.investments for update to authenticated using (true) with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'investments' and policyname = 'investments_delete_authenticated'
  ) then
    create policy investments_delete_authenticated on public.investments for delete to authenticated using (true);
  end if;
end
$$;

-- Storage policies for authenticated users.
do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'storage_objects_select_public_buckets'
  ) then
    create policy storage_objects_select_public_buckets
      on storage.objects
      for select
      to public
      using (bucket_id in ('product-images', 'profile_pictures'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'storage_objects_insert_authenticated'
  ) then
    create policy storage_objects_insert_authenticated
      on storage.objects
      for insert
      to authenticated
      with check (bucket_id in ('product-images', 'profile_pictures'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'storage_objects_update_authenticated'
  ) then
    create policy storage_objects_update_authenticated
      on storage.objects
      for update
      to authenticated
      using (bucket_id in ('product-images', 'profile_pictures'))
      with check (bucket_id in ('product-images', 'profile_pictures'));
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'storage_objects_delete_authenticated'
  ) then
    create policy storage_objects_delete_authenticated
      on storage.objects
      for delete
      to authenticated
      using (bucket_id in ('product-images', 'profile_pictures'));
  end if;
end
$$;

-- =========================
-- SEED DATA
-- =========================

insert into public.hog_raisers (name, phone, email, address, pig_type, status, lifecycle_stage)
values
  ('Mario Dela Cruz', '09171234567', 'mario.delacruz@piggytrunk.ph', 'Malasiqui, Pangasinan', 'Fattening', 'Active', 'Pre-Starter'),
  ('Rafael Santos', '09181234567', 'rafael.santos@piggytrunk.ph', 'Calasiao, Pangasinan', 'Sow', 'Active', 'Starter'),
  ('Joel Villanueva', '09191234567', 'joel.villanueva@piggytrunk.ph', 'San Carlos City, Pangasinan', 'Fattening', 'Inactive', 'Grower'),
  ('Ernesto Ramos', '09201234567', 'ernesto.ramos@piggytrunk.ph', 'Urdaneta City, Pangasinan', 'Sow', 'Active', 'Booster')
on conflict (lower(email)) do update
set
  name = excluded.name,
  phone = excluded.phone,
  address = excluded.address,
  pig_type = excluded.pig_type,
  status = excluded.status,
  lifecycle_stage = excluded.lifecycle_stage;

insert into public.inventory_products (name, category_id, category, image, description, price, units, sold, is_archived)
values
  ('Premium Hog Feed 25kg', 'feeds', 'Feeds', null, 'Balanced feed for grower stage hogs.', 1450.00, 80, 12, false),
  ('Vitamin Booster Mix', 'vitamins', 'Vitamins', null, 'Daily vitamin supplement mix.', 380.00, 45, 7, false),
  ('Deworming Syrup', 'medicines', 'Medicines', null, 'Routine deworming treatment.', 520.00, 30, 9, false),
  ('Farm Gloves (Pair)', 'others', 'Others', null, 'Protective gloves for handling.', 120.00, 150, 25, false)
on conflict do nothing;

commit;
