create table if not exists public.app_users (
  user_id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text,
  role text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  created_by bigint references public.app_users(user_id)
);

create index if not exists idx_app_users_role on public.app_users(role);
create index if not exists idx_app_users_status on public.app_users(status);
create table if not exists public.logs (
  logs_id bigint generated by default as identity primary key,
  status text,
  login_attempts integer not null default 0,
  user_id bigint not null references public.app_users(user_id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_logs_user_id on public.logs(user_id);
create table if not exists public.cashiers (
  cashier_id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  date_hired date not null default current_date
);
create table if not exists public.partner_investors (
  partner_investor_id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  address text,
  contact_number text,
  registration_date date not null default current_date
);
create table if not exists public.batches (
  batch_id bigint generated by default as identity primary key,
  batch_name text not null unique,
  date_created date not null default current_date
);
create table if not exists public.hog_types (
  hog_type_id bigint generated by default as identity primary key,
  type_name text not null unique,
  description text,
  ending_feed text
);
create table if not exists public.hog_raisers (
  hog_raiser_id bigint generated by default as identity primary key,
  address text,
  phone text,                  -- Changed from contact_number to match active code
  email text,                  -- Required by auth signup trigger
  account_status text not null default 'active',
  user_id bigint not null unique references public.app_users(user_id) on delete cascade,
  
  -- Performance Denormalization Columns (added for optimized dashboard reads)
  name text,
  pig_type text not null default 'Fattening',
  status text not null default 'Active',
  lifecycle_stage text not null default 'Booster'
);

create index if not exists idx_hog_raisers_status on public.hog_raisers(account_status);
create table if not exists public.hog_stages (
  stage_id bigint generated by default as identity primary key,
  stage_name text not null,
  feed_type text,
  stage_order integer not null,
  is_final boolean not null default false,
  hog_type_id bigint not null references public.hog_types(hog_type_id) on delete restrict,
  unique(hog_type_id, stage_order),
  unique(hog_type_id, stage_name)
);
create table if not exists public.assignments (
  assignment_id bigint generated by default as identity primary key,
  assigned_date date not null default current_date,
  status text not null default 'active',
  hog_type_id bigint not null references public.hog_types(hog_type_id) on delete restrict,
  batch_id bigint not null references public.batches(batch_id) on delete restrict,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete restrict
);

create index if not exists idx_assignments_raiser on public.assignments(hog_raiser_id);
create index if not exists idx_assignments_batch on public.assignments(batch_id);
create table if not exists public.hogs (
  hog_id bigint generated by default as identity primary key,
  status text not null default 'active',
  health_status text,
  last_updated timestamptz not null default now(),
  assignment_id bigint not null references public.assignments(assignment_id) on delete restrict,
  stage_id bigint references public.hog_stages(stage_id) on delete set null
);

create index if not exists idx_hogs_assignment on public.hogs(assignment_id);
create index if not exists idx_hogs_stage on public.hogs(stage_id);
create table if not exists public.hog_stage_logs (
  stage_log_id bigint generated by default as identity primary key,
  date_started date not null,
  date_ended date,
  hog_id bigint not null references public.hogs(hog_id) on delete cascade,
  stage_id bigint not null references public.hog_stages(stage_id) on delete restrict,
  check (date_ended is null or date_ended >= date_started)
);

create index if not exists idx_hog_stage_logs_hog on public.hog_stage_logs(hog_id);
create table if not exists public.stock_requests (
  request_id bigint generated by default as identity primary key,
  request_date date not null default current_date,
  status text not null default 'pending',
  decision_date date,
  assignment_id bigint not null references public.assignments(assignment_id) on delete restrict,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete restrict,
  category text not null default 'Feeds',
  quantity integer not null default 1,
  feed_type text,
  notes text
);

create index if not exists idx_stock_requests_assignment on public.stock_requests(assignment_id);
create table if not exists public.capital_infusions (
  capital_id bigint generated by default as identity primary key,
  amount numeric(14,2) not null check (amount >= 0),
  date_processed date not null default current_date,
  request_id bigint not null references public.stock_requests(request_id) on delete cascade
);

create index if not exists idx_capital_infusions_request on public.capital_infusions(request_id);
create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  current_stock integer not null default 0 check (current_stock >= 0),
  category text
);

create index if not exists idx_products_category on public.products(category);
create table if not exists public.supply (
  supply_id bigint generated by default as identity primary key,
  quantity_added integer not null check (quantity_added > 0),
  date_added date not null default current_date,
  product_id bigint not null references public.products(product_id) on delete restrict
);

create index if not exists idx_supply_product on public.supply(product_id);
  create table if not exists public.sales (
    sale_id bigint generated by default as identity primary key,
    quantity integer not null check (quantity > 0),
    total_amount numeric(14,2) not null check (total_amount >= 0),
    sale_date timestamptz not null default now(),
    type text,
    product_id bigint not null references public.products(product_id) on delete restrict,
    hog_raiser_id bigint references public.hog_raisers(hog_raiser_id) on delete set null,
    performed_by bigint not null references public.app_users(user_id) on delete restrict
  );

  create index if not exists idx_sales_product on public.sales(product_id);
  create index if not exists idx_sales_hog_raiser on public.sales(hog_raiser_id);
create table if not exists public.investments (
  investment_id bigint generated by default as identity primary key,
  amount numeric(14,2) not null check (amount >= 0),
  date_invested date not null default current_date,
  status text not null default 'active',
  batch_id bigint not null references public.batches(batch_id) on delete restrict,
  partner_investor_id bigint not null references public.partner_investors(partner_investor_id) on delete restrict
);

create index if not exists idx_investments_batch on public.investments(batch_id);
create index if not exists idx_investments_partner on public.investments(partner_investor_id);
alter table public.app_users
  add column if not exists supabase_user_id uuid unique;

alter table public.app_users
  add column if not exists must_change_password boolean not null default true;

alter table public.app_users
  add column if not exists password_reset_token text;

alter table public.app_users
  add column if not exists password_reset_sent_at timestamptz;

alter table public.app_users
  add column if not exists email_verified boolean not null default false;

comment on column public.app_users.supabase_user_id is 'Link to auth.users.id for Supabase Auth accounts';
comment on column public.app_users.must_change_password is 'Flag to require first-login password change for custom flows';
comment on column public.app_users.password_reset_token is 'Optional token for password reset flows';
comment on column public.app_users.password_reset_sent_at is 'Timestamp when reset token was issued';
comment on column public.app_users.email_verified is 'Tracks whether the email was verified via Supabase Auth.';

-- Add email column to hog_raisers (kung wala pa)
alter table public.hog_raisers 
  add column if not exists email text;
-- 19_inventory_products.sql
-- Creates the `inventory_products` table used by the Flutter Inventory and POS screens.

begin;

create table if not exists public.inventory_products (
  id          uuid            default gen_random_uuid() primary key,
  name        text            not null,
  category_id text,
  category    text            not null default 'Feeds',
  description text            not null default '',
  price       numeric(12,2)   not null default 0 check (price >= 0),
  units       integer         not null default 0 check (units >= 0),
  sold        integer         not null default 0 check (sold >= 0),
  image       text,
  is_archived boolean         not null default false,
  created_at  timestamptz     not null default now()
);

create index if not exists idx_inventory_products_category   on public.inventory_products(category);
create index if not exists idx_inventory_products_archived   on public.inventory_products(is_archived);
create index if not exists idx_inventory_products_created_at on public.inventory_products(created_at desc);

alter table public.inventory_products enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'inventory_products'
      and policyname = 'inventory_products_auth_all'
  ) then
    create policy inventory_products_auth_all
      on public.inventory_products
      for all to authenticated
      using (true) with check (true);
  end if;
end $$;

commit;
-- 20_investment_records.sql
-- Creates a denormalized `investment_records` table for the admin Investments screen.

begin;

create table if not exists public.investment_records (
  id              uuid            default gen_random_uuid() primary key,
  hog_raiser_id   text            not null,
  raiser_name     text            not null,
  initial_capital numeric(14,2)   not null default 0 check (initial_capital >= 0),
  hog_type        text            not null default 'Fattening',
  total_hog       integer         not null default 0 check (total_hog >= 0),
  investment_date date            not null default current_date,
  stage           text            not null default 'pending'
);

create index if not exists idx_investment_records_raiser on public.investment_records(hog_raiser_id);
create index if not exists idx_investment_records_date   on public.investment_records(investment_date desc);
create index if not exists idx_investment_records_stage  on public.investment_records(stage);

alter table public.investment_records enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'investment_records'
      and policyname = 'investment_records_auth_all'
  ) then
    create policy investment_records_auth_all
      on public.investment_records
      for all to authenticated
      using (true) with check (true);
  end if;
end $$;

commit;
-- 21_dashboard_summary_view.sql
-- Creates a PostgreSQL view used by the Flutter Dashboard screen to fetch
-- all KPI metrics (active raisers, batches, total capital, mortality, allocation)
-- in a single query.
-- Updated to check account_status = 'active' instead of status = 'active' for active raisers.

create or replace view public.dashboard_summary as
select
  -- KPI 1: Active Hog Raisers (based on approved account_status)
  (
    select count(*)::bigint
    from public.hog_raisers
    where lower(account_status) = 'active'
  ) as active_raisers,

  -- KPI 2: Number of Hog Batches
  (
    select count(*)::bigint
    from public.batches
  ) as batch_count,

  -- KPI 3: Total Current Investment (from investment_records)
  (
    select coalesce(sum(initial_capital), 0)
    from public.investment_records
  ) as total_capital,

  -- KPI 4: Number of Mortality (hogs with status = 'dead')
  (
    select count(*)::bigint
    from public.hogs
    where lower(status) = 'dead'
  ) as mortality_count,

  -- Allocation: Fattening capital
  (
    select coalesce(sum(initial_capital), 0)
    from public.investment_records
    where lower(hog_type) = 'fattening'
  ) as fattening_capital,

  -- Allocation: Sow capital
  (
    select coalesce(sum(initial_capital), 0)
    from public.investment_records
    where lower(hog_type) = 'sow'
  ) as sow_capital,

  -- Earliest investment date (used for "Start of Investment" KPI display)
  (
    select min(investment_date)
    from public.investment_records
  ) as start_of_investment;

-- Grant read access to authenticated users
grant select on public.dashboard_summary to authenticated;
-- 22_auth_signup_trigger.sql
-- Automatically syncs auth.users registrations to public tables with a 'Pending' status.
-- Simplified and made robust by removing ON CONFLICT clauses to prevent key/constraint index mismatch errors.
-- Updated to explicitly insert the email column in public.hog_raisers to satisfy NOT NULL constraints.
-- Updated status of hog_raisers to 'Active' to satisfy check constraints (account_status remains 'pending' for admin approval).
-- Updated to retrieve phone and address dynamically from user metadata.

create or replace function public.handle_new_user()
returns trigger as $$
declare
  new_app_user_id bigint;
  user_role text;
  user_name text;
  user_phone text;
  user_address text;
begin
  -- Default role to 'hog_raiser' if not specified in metadata
  user_role := coalesce(new.raw_user_meta_data->>'role', 'hog_raiser');
  
  -- Extract name, phone, and address from raw user metadata
  user_name := coalesce(
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'name',
    split_part(new.email, '@', 1)
  );
  user_phone := coalesce(new.raw_user_meta_data->>'phone', '');
  user_address := coalesce(new.raw_user_meta_data->>'address', '');

  -- Insert into public.app_users (Pending status unless admin)
  insert into public.app_users (name, email, role, status, supabase_user_id)
  values (
    user_name,
    new.email,
    user_role,
    case when user_role = 'admin' then 'active' else 'Pending' end,
    new.id
  )
  returning user_id into new_app_user_id;

  -- Insert into public.hog_raisers (using dynamic phone and address)
  if user_role = 'hog_raiser' then
    insert into public.hog_raisers (
      name, 
      email,
      phone, 
      pig_type, 
      status, 
      lifecycle_stage, 
      user_id, 
      account_status,
      address
    )
    values (
      user_name,
      new.email,
      user_phone, -- dynamic phone from metadata
      'Fattening', -- default
      'Active', -- allowed status value to pass check constraints
      'Booster', -- default stage
      new_app_user_id,
      'pending', -- admin approval status
      user_address -- dynamic address from metadata
    );
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Setup the trigger on auth.users
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();
-- 23_hog_raisers_foreign_key.sql
-- Removes duplicate constraint to prevent PostgREST PGRST201 embedding error.

begin;

alter table public.hog_raisers
  drop constraint if exists fk_hog_raisers_app_users;

commit;

-- Force PostgREST to reload the schema cache
notify pgrst, 'reload schema';
-- 24_inventory_logs.sql
-- Creates the `inventory_logs` table to track product operations like Add, Edit, Archive, and Restore.

begin;

create table if not exists public.inventory_logs (
  id            uuid            default gen_random_uuid() primary key,
  product_id    uuid            references public.inventory_products(id) on delete set null,
  product_name  text            not null,
  action        text            not null, -- 'ADD', 'UPDATE', 'ARCHIVE', 'RESTORE'
  performed_by  text            not null, -- Admin email or identifier
  price         numeric(12,2)   not null,
  units         integer         not null,
  details       text,                     -- Change descriptions
  created_at    timestamptz     not null default now()
);

create index if not exists idx_inventory_logs_product_id on public.inventory_logs(product_id);
create index if not exists idx_inventory_logs_created_at on public.inventory_logs(created_at desc);

alter table public.inventory_logs enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'inventory_logs'
      and policyname = 'inventory_logs_auth_all'
  ) then
    create policy inventory_logs_auth_all
      on public.inventory_logs
      for all to authenticated
      using (true) with check (true);
  end if;
end $$;

commit;
-- 1. Create admin_notifications table
create table if not exists public.admin_notifications (
  notification_id bigint generated by default as identity primary key,
  title text not null,
  message text not null,
  type text not null, -- 'stock_request', 'new_raiser'
  is_read boolean not null default false,
  metadata jsonb, -- e.g. { "request_id": 12, "hog_raiser_id": 3, "raiser_name": "Juan" }
  created_at timestamptz not null default now()
);

-- Index for unread notifications
create index if not exists idx_admin_notifications_unread 
  on public.admin_notifications(is_read) 
  where is_read = false;

-- 2. Trigger on stock_requests insert
create or replace function public.notify_admin_on_stock_request()
returns trigger as $$
declare
  raiser_name text;
begin
  select name into raiser_name 
  from public.hog_raisers 
  where hog_raiser_id = new.hog_raiser_id;

  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Stock Request',
    coalesce(raiser_name, 'A hog raiser') || ' has requested new stocks.',
    'stock_request',
    jsonb_build_object(
      'request_id', new.request_id,
      'hog_raiser_id', new.hog_raiser_id,
      'raiser_name', raiser_name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_stock_request_insert
after insert on public.stock_requests
for each row execute function public.notify_admin_on_stock_request();

-- 3. Trigger on hog_raisers insert
create or replace function public.notify_admin_on_new_raiser()
returns trigger as $$
begin
  insert into public.admin_notifications (title, message, type, metadata)
  values (
    'New Hog Raiser Registered',
    coalesce(new.name, 'A new raiser') || ' registered and is pending approval.',
    'new_raiser',
    jsonb_build_object(
      'hog_raiser_id', new.hog_raiser_id,
      'raiser_name', new.name
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_hog_raiser_insert
after insert on public.hog_raisers
for each row execute function public.notify_admin_on_new_raiser();

-- 4. Trigger on hog_raisers update (lifecycle_stage progress change)
create or replace function public.notify_admin_on_raiser_stage_update()
returns trigger as $$
begin
  if old.lifecycle_stage is distinct from new.lifecycle_stage and new.lifecycle_stage is not null then
    insert into public.admin_notifications (title, message, type, metadata)
    values (
      'Raiser Progress Updated',
      coalesce(new.name, 'A hog raiser') || ' has updated their progress stage to ' || new.lifecycle_stage || '.',
      'progress_update',
      jsonb_build_object(
        'hog_raiser_id', new.hog_raiser_id,
        'raiser_name', new.name,
        'old_stage', old.lifecycle_stage,
        'new_stage', new.lifecycle_stage
      )
    );
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_raiser_stage_update
after update of lifecycle_stage on public.hog_raisers
for each row execute function public.notify_admin_on_raiser_stage_update();
create table if not exists public.hog_reports (
  report_id bigint generated by default as identity primary key,
  hog_id bigint not null references public.hogs(hog_id) on delete cascade,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  report_type text not null,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_hog_reports_hog on public.hog_reports(hog_id);
create index if not exists idx_hog_reports_raiser on public.hog_reports(hog_raiser_id);

-- Enable RLS and allow all actions for simplicity during development
alter table public.hog_reports enable row level security;

create policy "Allow all on hog_reports"
on public.hog_reports
for all
using (true)
with check (true);
alter table public.hog_raisers
  add column if not exists avatar_url text;
-- Enable RLS on all app tables.
alter table public.app_users enable row level security;
alter table public.logs enable row level security;
alter table public.cashiers enable row level security;
alter table public.partner_investors enable row level security;
alter table public.batches enable row level security;
alter table public.hog_types enable row level security;
alter table public.hog_raisers enable row level security;
alter table public.hog_stages enable row level security;
alter table public.assignments enable row level security;
alter table public.hogs enable row level security;
alter table public.hog_stage_logs enable row level security;
alter table public.stock_requests enable row level security;
alter table public.capital_infusions enable row level security;
alter table public.products enable row level security;
alter table public.supply enable row level security;
alter table public.sales enable row level security;
alter table public.investments enable row level security;
alter table public.admin_notifications enable row level security;

-- Simple starter policy: authenticated users can read/write.
-- Tighten this later based on role rules.
do $$
declare
  t text;
  p text;
begin
  foreach t in array array[
    'app_users','logs','cashiers','partner_investors','batches','hog_types','hog_raisers',
    'hog_stages','assignments','hogs','hog_stage_logs','stock_requests','capital_infusions',
    'products','supply','sales','investments','admin_notifications'
  ]
  loop
    p := t || '_auth_all';
    if not exists (
      select 1
      from pg_policies
      where schemaname = 'public'
        and tablename = t
        and policyname = p
    ) then
      execute format(
        'create policy %I on public.%I for all to authenticated using (true) with check (true);',
        p,
        t
      );
    end if;
  end loop;
end $$;


-- ==========================================
-- 28_auto_batch_assignment.sql (Auto-Batch Triggers)
-- ==========================================

create or replace function public.fn_auto_create_batch_and_assignment()
returns trigger as $$
declare
  v_hog_type_id bigint;
  v_batch_id bigint;
  v_assignment_id bigint;
  v_stage_id bigint;
  i integer;
begin
  -- 1. Get or create hog_type
  select hog_type_id into v_hog_type_id
  from public.hog_types
  where lower(type_name) = lower(new.hog_type)
  limit 1;
  
  if v_hog_type_id is null then
    insert into public.hog_types (type_name, description)
    values (new.hog_type, 'Auto-generated from investment')
    returning hog_type_id into v_hog_type_id;
  end if;

  -- 2. Create a unique batch name linked to the investment UUID
  insert into public.batches (batch_name, date_created)
  values (new.raiser_name || ' - ' || to_char(new.investment_date, 'Mon DD, YYYY') || ' - ' || new.hog_type || ' (' || new.id::text || ')', new.investment_date)
  returning batch_id into v_batch_id;

  -- 3. Create the assignment linking raiser, batch, and type
  insert into public.assignments (assigned_date, status, hog_type_id, batch_id, hog_raiser_id)
  values (new.investment_date, 'active', v_hog_type_id, v_batch_id, (new.hog_raiser_id)::bigint)
  returning assignment_id into v_assignment_id;

  -- 4. Get the initial 'Booster' stage for this hog type if exists
  select stage_id into v_stage_id
  from public.hog_stages
  where hog_type_id = v_hog_type_id
    and lower(stage_name) = 'booster'
  limit 1;

  -- 5. Automatically insert the hogs for this batch
  for i in 1..new.total_hog loop
    insert into public.hogs (status, health_status, assignment_id, stage_id)
    values ('active', 'Healthy', v_assignment_id, v_stage_id);
  end loop;

  return new;
end;
$$ language plpgsql;

create or replace trigger trg_auto_create_batch_and_assignment
after insert on public.investment_records
for each row
execute function public.fn_auto_create_batch_and_assignment();


create or replace function public.fn_auto_delete_batch_and_assignment()
returns trigger as $$
declare
  v_batch_name_pattern text;
  v_batch_id bigint;
begin
  v_batch_name_pattern := '%(' || old.id::text || ')';
  
  -- Find the batch_id
  select batch_id into v_batch_id
  from public.batches
  where batch_name like v_batch_name_pattern
  limit 1;
  
  if v_batch_id is not null then
    -- Delete stage logs associated with hogs of this assignment
    delete from public.hog_stage_logs
    where hog_id in (
      select hog_id from public.hogs 
      where assignment_id in (select assignment_id from public.assignments where batch_id = v_batch_id)
    );

    -- Delete hogs associated with the assignments for this batch
    delete from public.hogs
    where assignment_id in (select assignment_id from public.assignments where batch_id = v_batch_id);
    
    -- Delete assignments for this batch
    delete from public.assignments
    where batch_id = v_batch_id;
    
    -- Delete the batch
    delete from public.batches
    where batch_id = v_batch_id;
  end if;
  
  return old;
end;
$$ language plpgsql;

create or replace trigger trg_auto_delete_batch_and_assignment
after delete on public.investment_records
for each row
execute function public.fn_auto_delete_batch_and_assignment();


-- ==========================================
-- 29_raiser_notifications.sql (Raiser Notifications)
-- ==========================================

create table if not exists public.raiser_notifications (
  notification_id bigint generated by default as identity primary key,
  hog_raiser_id bigint not null references public.hog_raisers(hog_raiser_id) on delete cascade,
  title text not null,
  message text not null,
  type text not null,
  is_read boolean not null default false,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_raiser_notifications_unread 
  on public.raiser_notifications(hog_raiser_id, is_read) 
  where is_read = false;

alter table public.raiser_notifications enable row level security;

create policy raiser_notifications_auth_all on public.raiser_notifications
  for all to authenticated
  using (true)
  with check (true);

create or replace function public.notify_raiser_on_request_update()
returns trigger as $$
begin
  if (old.status is distinct from new.status) then
    insert into public.raiser_notifications (hog_raiser_id, title, message, type, metadata)
    values (
      new.hog_raiser_id,
      'Stock Request Update',
      'Your request for ' || new.quantity || ' ' || coalesce(new.category, 'supplies') || ' has been ' || lower(new.status) || '.',
      'request_status',
      jsonb_build_object(
        'request_id', new.request_id,
        'status', new.status,
        'category', new.category,
        'quantity', new.quantity
      )
    );
  end if;
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_stock_request_update
after update of status on public.stock_requests
for each row execute function public.notify_raiser_on_request_update();

create or replace function public.notify_raiser_on_investment()
returns trigger as $$
begin
  insert into public.raiser_notifications (hog_raiser_id, title, message, type, metadata)
  values (
    (new.hog_raiser_id)::bigint,
    'New Batch Assigned',
    'A new active batch of ' || new.total_hog || ' ' || new.hog_type || ' has been assigned to you.',
    'batch_assigned',
    jsonb_build_object(
      'investment_id', new.id,
      'hog_type', new.hog_type,
      'total_hog', new.total_hog
    )
  );
  return new;
end;
$$ language plpgsql;

create or replace trigger trigger_on_investment_insert
after insert on public.investment_records
for each row execute function public.notify_raiser_on_investment();


